### DISCUSSION TITLE
docker: shlink-task-worker-x shows 100% CPU in htop

### DISCUSSION THREAD

**Discussion by michabbb** [shlinkio/discussions#115] [Help wanted] [answered]
hi, 

i am using the docker image `shlink:stable` (v2.6.2) with mysql.
while watching htop (on the host) i noticed:

![image](https://user-images.githubusercontent.com/3524595/133480631-56d93157-1388-49ab-91a1-cf414d2d7280.png)

and I am surprised because the server only has 200 visits a day.
so: is this "normal" that these workers take so much CPU ???

thanks for any help!

**Comment by acelaya** [comment]
No, that shouldn't be the case. Have you tried restarting Shlink?

**Reply by michabbb** [reply]
after a restart, it looks okay:

![image](https://user-images.githubusercontent.com/3524595/133924991-3f454b5b-4799-4ded-b08b-3779aeccae2d.png)

i will keep an 👁️ on this... 🤔

**Reply by acelaya** [reply]
Thanks!

I'm not sure what could be the reason. The task workers only geolocate visits, which is usually super fast.

They also download updated versions of the GeoLite db. Did you provide your own license key?

**Reply by michabbb** [reply]
yes, i do ;)

**Reply by paolobasso99** [reply]
I just checked and it happened to me as well. After restart everything is ok.

I am using shlink inside docker on an ubuntu vps and I did provide my own license key as well.

**Reply by acelaya** [reply]
I would need to know after how much time do you notice this starts to happen, and what is the config you provide to the container.

**Reply by paolobasso99** [reply]
I am running a single host shlink container using docker-compose and keeping almost all configuration to default. The instance was running for abount 2 months and I do not know when the issue started, if it happens again I will inform you.

This is the service defined in my `docker-compose.yml`:
```
shlink_api:
    image: shlinkio/shlink:stable
    container_name: shlink_api
    depends_on:
      - shlink_db
    environment:
      - SHORT_DOMAIN_HOST=${SHLINK_API_SUBDOMAIN}.${SHLINK_BASEDOMAIN}
      - SHORT_DOMAIN_SCHEMA=https
      - GEOLITE_LICENSE_KEY=${SHLINK_GEOLITE_LICENSE_KEY}
      - DEFAULT_BASE_URL_REDIRECT=https://${SHLINK_BASEDOMAIN}
      - DB_DRIVER=postgres
      - DB_NAME=shlink
      - DB_USER=shlink
      - DB_PASSWORD=${SHLINK_DB_PASSWORD}
      - DB_HOST=shlink_db
    restart: unless-stopped
    labels:
      - traefik proxy labels ...
    networks:
      - web_proxy
      - shlink
```

The server is on version 2.10.1, I will now update it and report back if the issue reapears.
