### DISCUSSION TITLE
Docker pull does not return the latest version

### DISCUSSION THREAD

**Discussion by FraanCIB** [shlinkio/discussions#13] [Help wanted]
### shlink-web-client version

3.10.2

### How do you use shlink-web-client

Docker image

### Summary

Hello, I pulled my docker compose and the version on the website still shows me 3.10.2
Do I need to do anything different apart from the pull and up?

**Comment by acelaya** [comment]
Running `docker pull` will only pull the tags you already have. Can you be more specific on how you "pulled" and how you use the docker image?

**Comment by FraanCIB** [comment]
i have the docker compose, and i have with caddy proxy.

```
version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: always
    hostname: shlinkapi
    environment:
      - TZ="Europe/Madrid"
      - DEFAULT_DOMAIN=c
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=
      - DB_DRIVER=
      - DB_USER=
      - DB_NAME=
      - DB_PASSWORD=
      - DB_HOST=
    depends_on:
      - database
    networks:
      - app
      - proxy
    # ports:
    #   - <127.0.0.1>:<8080>:8080

  database:
    image: mariadb:10.8
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=
      - MARIADB_DATABASE=
      - MARIADB_USER=
      - MARIADB_PASSWORD=
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app
  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: always
    hostname: shlinkfront
    environment:
      - SHLINK_SERVER_URL=
      - SHLINK_SERVER_API_KEY=
    networks:
      - proxy

networks:
  app:
  proxy:
    external:
      name: caddy
volumes:
  db_data:
```
  
to update I always do a docker compose pull of the images and then do a docker compose up -d to update it
