### DISCUSSION TITLE
Can't connect more than one person to the server

### DISCUSSION THREAD

**Discussion by dsipetcher** [shlinkio/discussions#168] [Help wanted] [answered]
### Shlink version

4.2.0

### PHP version

8.3.0

### How do you serve Shlink

Docker image

### Database engine

PostgreSQL

### Database version

16.0

### Summary

I can connect to the self hosted shlink server both throughh the self hosted web client and shlink.io. But anyone else can't connect to the server, and server and client is running from the image so I can't imagine what could possibly go wrong

**Comment by franco640** [comment]
Hi, 

I hate to ask, but could you provide a docker compose file of your setup, excluding any sensitive info of course. I'm having issues setting this up and have posted a message with no response for some time. Furthermore, I would really appreciate your assistance on where I went wrong 

Thanks

**Reply by dsipetcher** [reply]
Hi, I will be happy to provide that, just struggle to find it honestly, I will send at the moment I will find it))

**Reply by dsipetcher** [reply]
@franco640 Hello, I ended up starting a new one instance, but my problem stays.
I did it by running folowwing commands:
docker run \
    --name my_shlink \
    -p 8083:8080 \
    -e DEFAULT_DOMAIN=creobit.com \
    -e IS_HTTPS_ENABLED=true \
    shlinkio/shlink:stable

docker run \
    --name shlink-web-client \
    -p 8000:8080 \
    -e SHLINK_SERVER_URL=https://creobit.com \
    -e SHLINK_SERVER_API_KEY= our API key \
    shlinkio/shlink-web-client
    
And redirects are configured by this nginx confs:
For the shlink - 
`
server {
    listen 80;
    listen [::]:80;
    server_name creobit.com www.creobit.com;

    location / {
	return 301 https://creobit.com;
    }

    server_tokens off;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name creobit.com;

    # SSL РЅР°СЃС‚СЂРѕР№РєРё
    ssl_certificate /etc/letsencrypt/live/creobit.com-0001/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/creobit.com-0001/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Р РµРґРёСЂРµРєС‚ СЃ www РЅР° РѕСЃРЅРѕРІРЅРѕР№ РґРѕРјРµРЅ
    if ($host = 'www.creobit.com') {
        return 301 https://creobit.com$request_uri;
    }

    location / {
        proxy_pass http://localhost:8083;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE";
        add_header Access-Control-Allow-Headers "Authorization, Content-Type";
        
        # ? Handle OPTIONS requests properly
        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}


`
And for the web client - 
`
# HTTP -> HTTPS Redirection
server {
    if ($host = shlink.creobit.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name shlink.creobit.com; # CHANGE HERE
 
    # Location for Let's Encrypt validation
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
 
    return 301 https://$host$request_uri;  # Redirect all traffic to HTTPS


}
 
# HTTPS Configuration
server {
    charset utf-8;
    listen 443 ssl;
    server_name shlink.creobit.com; # CHANGE HERE
 
    
    # Proxy requests to Shlink running on port 8000
    location / {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
 
        # WebSocket Support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
   
 
    # Optional Access/Error Logging
    access_log /var/log/nginx/shlink.creobit.com.log; # CHANGE HERE
    error_log /var/log/nginx/shlink.creobit.com.log; # CHANGE HERE

    ssl_certificate /etc/letsencrypt/live/shlink.creobit.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/shlink.creobit.com/privkey.pem; # managed by Certbot
}
server {
    listen 8083 default_server;
    charset utf-8;
    root /usr/share/nginx/html;
    index index.html;

    # Expire rules for static content
    # HTML files should never be cached. There's only one here, which is the entry point (index.html)
    location ~* \.(?:manifest|appcache|html?|xml|json)$ {
       expires -1;
    }
    # Images and other binary assets can be saved for a month
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1M;
        add_header Cache-Control "public";
    }
    # JS and CSS files can be saved for a year, as they are always hashed. New versions will include a new hash anyway, forcing the download
    location ~* \.(?:css|js)$ {
        expires 1y;
        add_header Cache-Control "public";
    }

    # servers.json may be on the root, or in conf.d directory
    location = /servers.json {
        try_files /servers.json /conf.d/servers.json;
    }

    # When requesting static paths with extension, try them, and return a 404 if not found
    location ~* .+\.(css|js|html|png|jpe?g|gif|bmp|ico|json|csv|otf|eot|svg|svgz|ttf|woff|woff2|ijmap|pdf|tif|map) {
        try_files $uri $uri/ =404;
    }
    # When requesting a path without extension, try it, and return the index if not found
    # This allows HTML5 history paths to be handled by the client application
    location / {
        try_files $uri $uri/ /index.html$is_args$args;
    }
}
`
Will be happy to provide more info if needed)))

**Reply by dsipetcher** [reply]
@franco640  I can also send info in more readble way if you need it)

**Reply by franco640** [reply]
@dsipetcher 

Thankyou sooo much for posting on this ;-)

If you could send the info in a more readable way I would very much appreciate that. 

See you just did a basic docker compose file and externally did the web client etc as base nginx format. Did you not do all of it under a Docker file using caddy etc 

Thanks

**Reply by dsipetcher** [reply]
[nginx_conf_web.txt](https://github.com/user-attachments/files/19936203/nginx_conf_web.txt)
[nginx_conf.txt](https://github.com/user-attachments/files/19936205/nginx_conf.txt)
I did both conteiners by the commands from the img:
docker run
--name my_shlink
-p 8083:8080
-e DEFAULT_DOMAIN=creobit.com
-e IS_HTTPS_ENABLED=true
shlinkio/shlink:stable

docker run
--name shlink-web-client
-p 8000:8080
-e SHLINK_SERVER_URL=https://creobit.com/
-e SHLINK_SERVER_API_KEY= our API key
shlinkio/shlink-web-client

And I did all of the nginx configuration by myself by using my past conf files and editing them for the slink and web client
@franco640 will be looking forward for your answers or info requests)))

**Reply by franco640** [reply]
@dsipetcher What database did you use? Mysql, mongo etc  it's mention on the documentation not to use the default for production 

here was my docker compose file using mysql

```
version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD= # My Password
      - MYSQL_DATABASE=shlink
      - MYSQL_USER=shlink_user
      - MYSQL_PASSWORD=# My Password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      shlink_net:
        ipv4_address: 172.19.0.5

  shlink:
    image: ghcr.io/shlinkio/shlink:stable  # ✅ Using GHCR instead of Docker Hub
    container_name: shlink
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DEFAULT_DOMAIN= # My Domain (This is valid and working on DNS)
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY= # My key 
      - DB_DRIVER=mysql
      - DB_USER=shlink_user
      - DB_PASSWORD=# My Password
      - DB_NAME=shlink
      - DB_HOST=mysql
      - DB_PORT=3306
      - SHELL_VERBOSITY=3
    command: ["./bin/rr", "serve", "-c", "config/roadrunner/.rr.yml"]
    ports:
      - "8080:8080"
    networks:
      shlink_net:
        ipv4_address: 172.19.0.3

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN= # My Domain (This is valid and working on DNS)
    networks:
      shlink_net:
        ipv4_address: 172.19.0.4

  shlink-web:
    image: shlinkio/shlink-web-client:latest
    container_name: shlink-web
    restart: unless-stopped
    environment:
      - SHLINK_SERVER_URL= # My Domain (This is valid and working on DNS)
      - SHLINK_SERVER_API_KEY= # My key   05172ad5-********
      - SHLINK_SERVER_NAME= # Shlink
    ports:
      - "8081:80"  # ✅ Maps host 8081 -> container 80
    networks:
      shlink_net:
        ipv4_address: 172.19.0.2

networks:
  shlink_net:
    name: shlink_net
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.0.0/16"  # Subnet for the custom network

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
```
