### DISCUSSION TITLE
[WARNING] A geolocation db is already being downloaded by another process

### DISCUSSION THREAD

**Discussion by Inetov** [shlinkio/discussions#177] [Help wanted] [answered]
### Shlink version

4.4.6

### PHP version

8.4.5

### How do you serve Shlink

Self-hosted Apache

### Database engine

MariaDB

### Database version

11.7.2

### Current behavior

I noticed that the country and city definition stopped working.
updated Shlink to the latest version, tried to execute the command
`docker exec -it my_shlink shlink visit:locate -vvv`
got the result:

```
 [WARNING] A geolocation db is already being downloaded by another process.

Processing IP 164.92.71.0

 [ERROR] The file "/etc/shlink/config/autoload/../../data/GeoLite2-City.mmdb" does not exist or is not readable.

In Reader.php line 91:

  [InvalidArgumentException]
  The file "/etc/shlink/config/autoload/../../data/GeoLite2-City.mmdb" does not exist or is not readable.

Exception trace:
  at /etc/shlink/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php:91
 MaxMind\Db\Reader->__construct() at /etc/shlink/vendor/geoip2/geoip2/src/Database/Reader.php:69
 GeoIp2\Database\Reader->__construct() at /etc/shlink/vendor/shlinkio/shlink-ip-geolocation/src/GeoLite2/GeoLite2ReaderFactory.php:21
 Shlinkio\Shlink\IpGeolocation\GeoLite2\GeoLite2ReaderFactory->__invoke() at /etc/shlink/vendor/shlinkio/shlink-ip-geolocation/src/Resolver/GeoLite2LocationResolver.php:34
 Shlinkio\Shlink\IpGeolocation\Resolver\GeoLite2LocationResolver->resolveIpLocation() at /etc/shlink/vendor/shlinkio/shlink-ip-geolocation/src/Resolver/ChainIpLocationResolver.php:29
 Shlinkio\Shlink\IpGeolocation\Resolver\ChainIpLocationResolver->resolveIpLocation() at /etc/shlink/module/Core/src/Visit/Geolocation/VisitToLocationHelper.php:35
 Shlinkio\Shlink\Core\Visit\Geolocation\VisitToLocationHelper->resolveVisitLocation() at /etc/shlink/module/CLI/src/Command/Visit/LocateVisitsCommand.php:139
 Shlinkio\Shlink\CLI\Command\Visit\LocateVisitsCommand->geolocateVisit() at /etc/shlink/module/Core/src/Visit/Geolocation/VisitLocator.php:49
 Shlinkio\Shlink\Core\Visit\Geolocation\VisitLocator->locateVisits() at /etc/shlink/module/Core/src/Visit/Geolocation/VisitLocator.php:24
 Shlinkio\Shlink\Core\Visit\Geolocation\VisitLocator->locateUnlocatedVisits() at /etc/shlink/module/CLI/src/Command/Visit/LocateVisitsCommand.php:112
 Shlinkio\Shlink\CLI\Command\Visit\LocateVisitsCommand->lockedExecute() at /etc/shlink/module/CLI/src/Command/Util/AbstractLockedCommand.php:35
 Shlinkio\Shlink\CLI\Command\Util\AbstractLockedCommand->execute() at /etc/shlink/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /etc/shlink/vendor/symfony/console/Application.php:1076
 Symfony\Component\Console\Application->doRunCommand() at /etc/shlink/vendor/symfony/console/Application.php:342
 Symfony\Component\Console\Application->doRun() at /etc/shlink/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->run() at /etc/shlink/bin/cli:10
```

command `visit:download-db`
says `[WARNING] A geolocation db is already being downloaded by another process.`

### Expected behavior

country and city definition works) commands also work.

**Comment by acelaya** [comment]
Closing, as no steps to reproduce were provided. I'm happy to reopen when provided.

**Comment by Inetov** [comment]
> no steps to reproduce were provided

can you try updating from a version about half a year ago?
I didn't do anything strange, all the settings correspond to the instructions on the site, it worked without problems before.
I don't know what version was installed (image: `shlinkio/shlink:stable`)

**Comment by Inetov** [comment]
Also, I looked at the download history on maxmind.com and found that there were no downloads since 2025-03-01 and one appeared today after the update.

**Comment by Inetov** [comment]
@acelaya I still have this problem: location always "Unknown".

I tried to delete the old container, pull the new version and create it again (I didn't change only the compose file and the DB).

current version: `Shlink 4.5.2`
in the download history on maxmind.com there are no attempts for several months.

-----------------------------------------------------
result of executing the commands:


`shlink -vvv visit:download-db`:


` [WARNING] A geolocation db is already being downloaded by another process.`


------------------------------------


`shlink -vvv visit:locate`:

```
 [WARNING] A geolocation db is already being downloaded by another process.

Processing IP 164.92.71.0

 [ERROR] The file "/etc/shlink/config/autoload/../../data/GeoLite2-City.mmdb" does not exist or is not readable.

In Reader.php line 91:

  [InvalidArgumentException]
  The file "/etc/shlink/config/autoload/../../data/GeoLite2-City.mmdb" does not exist or is not readable.

Exception trace:
  at /etc/shlink/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php:91
 MaxMind\Db\Reader->__construct() at /etc/shlink/vendor/geoip2/geoip2/src/Database/Reader.php:65
 GeoIp2\Database\Reader->__construct() at /etc/shlink/vendor/shlinkio/shlink-ip-geolocation/src/GeoLite2/GeoLite2ReaderFactory.php:21
 Shlinkio\Shlink\IpGeolocation\GeoLite2\GeoLite2ReaderFactory->__invoke() at /etc/shlink/vendor/shlinkio/shlink-ip-geolocation/src/Resolver/GeoLite2LocationResolver.php:34
 Shlinkio\Shlink\IpGeolocation\Resolver\GeoLite2LocationResolver->resolveIpLocation() at /etc/shlink/vendor/shlinkio/shlink-ip-geolocation/src/Resolver/ChainIpLocationResolver.php:29
 Shlinkio\Shlink\IpGeolocation\Resolver\ChainIpLocationResolver->resolveIpLocation() at /etc/shlink/module/Core/src/Visit/Geolocation/VisitToLocationHelper.php:35
 Shlinkio\Shlink\Core\Visit\Geolocation\VisitToLocationHelper->resolveVisitLocation() at /etc/shlink/module/CLI/src/Command/Visit/LocateVisitsCommand.php:138
 Shlinkio\Shlink\CLI\Command\Visit\LocateVisitsCommand->geolocateVisit() at /etc/shlink/module/Core/src/Visit/Geolocation/VisitLocator.php:49
 Shlinkio\Shlink\Core\Visit\Geolocation\VisitLocator->locateVisits() at /etc/shlink/module/Core/src/Visit/Geolocation/VisitLocator.php:24
 Shlinkio\Shlink\Core\Visit\Geolocation\VisitLocator->locateUnlocatedVisits() at /etc/shlink/module/CLI/src/Command/Visit/LocateVisitsCommand.php:111
 Shlinkio\Shlink\CLI\Command\Visit\LocateVisitsCommand->lockedExecute() at /etc/shlink/module/CLI/src/Command/Util/AbstractLockedCommand.php:34
 Shlinkio\Shlink\CLI\Command\Util\AbstractLockedCommand->execute() at /etc/shlink/vendor/symfony/console/Command/Command.php:318
 Symfony\Component\Console\Command\Command->run() at /etc/shlink/vendor/symfony/console/Application.php:1074
 Symfony\Component\Console\Application->doRunCommand() at /etc/shlink/vendor/symfony/console/Application.php:341
 Symfony\Component\Console\Application->doRun() at /etc/shlink/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->run() at /etc/shlink/bin/cli:10

visit:locate [-r|--retry] [-a|--all]
```
----------------------------------------------------------------------------------

I check inside container:  (I suppose `/etc/shlink/config/../../data/` = `/etc/shlink/data/`)
```
ls -lah /etc/shlink/data/
total 32K
drwxr-xr-x    1 1001     1001        4.0K Aug 27 07:46 .
drwxr-xr-x    1 root     root        4.0K Aug 27 07:49 ..
drwxr-xr-x    2 1001     1001        4.0K Aug 27 07:46 cache
drwxr-xr-x    1 1001     1001        4.0K Aug 31 09:32 locks
drwxr-xr-x    2 1001     1001        4.0K Aug 27 07:46 log
drwxr-xr-x    1 1001     1001        4.0K Aug 31 09:36 proxies
```

what else can i provide?

**Comment by acelaya** [comment]
> [WARNING] A geolocation db is already being downloaded by another process.

This seems to be the key. Shlink thinks the database file is being downloaded. This is likely due to some outdated lock file that was left "behind" for some reason, probably related with user permissions.

Try deleting any files inside the `data/locks` folder which have `geolocation-db-update` anywhere on their name.

**Reply by Inetov** [reply]
I deleted the file and ran it again:
```
/etc/shlink/data/locks $ ls -lah
total 12K
drwxr-xr-x    1 1001     1001        4.0K Sep  1 07:51 .
drwxr-xr-x    1 1001     1001        4.0K Aug 27 07:46 ..
-rw-rw-rw-    1 1001     root           0 Aug 31 17:53 sf.db-create.rYoFOz0.lock
-rw-rw-rw-    1 1001     root           0 Aug 31 17:53 sf.db-migrate.LvsXpxV.lock
-rw-rw-rw-    1 1001     root           0 Aug 31 17:54 sf.visit-locate.9Dn+U7W.lock
/etc/shlink/data/locks $ shlink -vvv visit:download-db


 [WARNING] A geolocation db is already being downloaded by another process.


/etc/shlink/data/locks $ ls -lah
total 12K
drwxr-xr-x    1 1001     1001        4.0K Sep  1 07:52 .
drwxr-xr-x    1 1001     1001        4.0K Aug 27 07:46 ..
-rw-rw-rw-    1 1001     root           0 Aug 31 17:53 sf.db-create.rYoFOz0.lock
-rw-rw-rw-    1 1001     root           0 Aug 31 17:53 sf.db-migrate.LvsXpxV.lock
-rw-rw-rw-    1 1001     root           0 Sep  1 07:52 sf.geolocation-db-update.UVCVIku.lock
-rw-rw-rw-    1 1001     root           0 Aug 31 17:54 sf.visit-locate.9Dn+U7W.lock
```

same.


> This is likely due to some outdated lock file that was left "behind" for some reason, probably related with user permissions.

how is this possible if it's inside a container that I rebuilt from the latest image?
I don't have any mounts for this container.

**Reply by acelaya** [reply]
> how is this possible if it's inside a container that I rebuilt from the latest image?

Then I guess this is wrong?

> ### How do you serve Shlink
>
> Self-hosted Apache

Can you provide precise information of how you run Shlink? If you are using the docker image, can you provide a reproduction in the form of a docker compose config? This same issue could also be caused by some kind of filesystem restriction when running the docker images.

**Reply by Inetov** [reply]
yes, sorry, it's docker:

```yaml
name: shlink

services:
  db:
    labels:
      io.portainer.accesscontrol.users: admin
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=my-secret-pw
    volumes:
      - /opt/shlink/mariadb_data/:/var/lib/mysql:Z
      - "./my.cnf:/etc/mysql/my.cnf"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  shlink:
    labels:
      io.portainer.accesscontrol.users: admin
    container_name: my_shlink
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:8080"
    environment:
      - DEFAULT_DOMAIN=<MY_DOMAIN>
      - INITIAL_API_KEY=<MY_INIT_KEY_DOUBLE_CHECKED>
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=<MY_GEO_API_KEY_DOUBLE_CHECKED>
      - DB_DRIVER=maria
      - DB_NAME=shlink
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_HOST=db
      - DB_PORT=3306
      - MEMORY_LIMIT=100M
      - SHELL_VERBOSITY=3
    image: shlinkio/shlink:stable
    depends_on:
      db:
        condition: service_healthy
        restart: true
```
