### DISCUSSION TITLE
docker compose with mariadb

### DISCUSSION THREAD

**Discussion by yodaphone** [shlinkio/discussions#41] [Help wanted]
can someone help me with a docker compose with mariadb? this is my compose file. 

```
version: '3'

services:
  mariadb:
    image: 'mariadb:latest'
    restart: 'always'
    container_name: 'mariadb'
    environment:
      MYSQL_ROOT_PASSWORD: 'rvKq6Y83w9p'
    volumes:
      - dbdata:/var/lib/mysql

  shlink:
    image: shlinkio/shlink:stable
    container_name: my_shlink
    ports:
      - 8080:8080
    links:
      - mariadb
    environment:
      SHORT_DOMAIN_HOST: 'url.domain.com'
      SHORT_DOMAIN_SCHEMA: 'https'
      GEOLITE_LICENSE_KEY: 'STfJXnuqO0SNGb12'
      DB_DRIVER: 'maria'
      DB_USER: 'root'
      DB_PASSWORD: 'rvKq6Y83w9p'
      DB_HOST: 'mariadb'
      DB_PORT: '3306'
    restart: always

volumes:
  dbdata:

```
why i run it i get this error

```
my_shlink  |
my_shlink  | In AbstractMySQLDriver.php line 112:
my_shlink  |
my_shlink  |   An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for u
my_shlink  |   ser 'root'@'172.23.0.3' (using password: YES)
my_shlink  |
my_shlink  |
my_shlink  | In Exception.php line 18:
my_shlink  |
my_shlink  |   SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.23.0.3' (using pa
my_shlink  |   ssword: YES)
my_shlink  |
my_shlink  |
my_shlink  | In PDOConnection.php line 38:
my_shlink  |
my_shlink  |   SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.23.0.3' (using pa
my_shlink  |   ssword: YES)
my_shlink  |
my_shlink  |
my_shlink  | db:create
my_shlink  |
mariadb    | 2021-04-19 17:28:45 5 [Warning] Access denied for user 'root'@'172.23.0.3' (using password: YES)
mariadb    | 2021-04-19 17:28:45 6 [Warning] Access denied for user 'root'@'172.23.0.3' (using password: YES)

```
