### DISCUSSION TITLE
Redis configuration

### DISCUSSION THREAD

**Discussion by rtrompier** [shlinkio/discussions#57] [Help wanted] [answered]
#### How Shlink is set-up

* Shlink Version: 2.10.1
* PHP Version: N.C
* How do you serve Shlink: Docker image
* Database engine used: PostgreSQL

#### Summary

Hello,
We use Shlink in a cluster mode with 2 instances, and one redis server.
Sometimes, we can see somes OOM for our Redis instance.
Wich sizing and TTL configuration do you suggest to use for redis server ? 

**Current Redis resources limitations :** 
```
resources:
        limits:
          cpus: "1"
          memory: 512M
```

**Current Redis TTL configuration :** 
```
save 900 1
save 300 10
save 60 10000
```

**Comment by acelaya** [comment]
At the moment Shlink is barely using Redis for anything. I plan to change this to apply performance improvements when possible, but I find very unlikely that those memory issues are caused by Shlink.

It could be using 1% of those 512Mb, tops.

Are you maybe using that Redis instance for something else?

**Comment by acelaya** [comment]
Maybe this helps deciding how much memory to allocate https://docs.redis.com/latest/rs/administering/designing-production/hardware-requirements/, but according to that, Redis recommends way more than 512Mb.

**Comment by rtrompier** [comment]
Hi, and many thanks for the quick reply
We have increase the RAM to 4GB and it should be better.

In the Redis logs, we can see it persist more than "1% of the resource". Do you have the same things on your side ? 
![image](https://user-images.githubusercontent.com/2504924/148518307-62fae1a8-f7fe-4ed9-a84b-14b6ae95ce0e.png)

In the same time, we have started a stress test on the Shlink cluster with 10000 queries, and we can see the memory usage is increasing with never flush it. Can you reproduce the same issue ?

**Reply by acelaya** [reply]
Hmm, that's unexpected. Shlink is not actively using that much.

Shlink is currently using some abstractions to interact with redis, and I know some other Shlink dependencies rely on the same abstractions.

I'm wondering if there are some extra unintended usages. I'll investigate.

**Comment by acelaya** [comment]
I can confirm the database abstraction layer is also using redis when configured, and it creates cache entries that never expire, but I suspect they are not always relevant, because it grows and grows as long as you create new URLs.

It is possible to set a default lifetime, though, so I'm going to do it.

**Comment by acelaya** [comment]
I have marked this discussion as resolved. You can follow-up the resolution of the bug here https://github.com/shlinkio/shlink/issues/1308

**Comment by acelaya** [comment]
I have just released v2.10.2 (the docker image will be available once [this build](https://github.com/shlinkio/shlink/runs/4743595552?check_suite_focus=true) finishes).

This release adds a 24h lifetime for cache entries. That should mitigate the issue for a regular Shlink usage.

**Reply by acelaya** [reply]
Hey @rtrompier @chirogocki did you have the chance to try with Shlink 2.10.2? Does it clear the cache every 24h as expected? Is it still caching too much during those 24h?

**Reply by rtrompier** [reply]
Hi @acelaya 

Many thanks for the new version.
The stress test is in progress with the latest version ;) 

I come back to you when I have a feedback.

**Reply by acelaya** [reply]
The workaround won't have an impact on a stress test context, as the cache entries expire after 24h. If you create 10k URLs in one go, it will still consume more memory in redis.

It would be good to know if you no longer see redis running out of memory for a real use-case.

However, if you expect that kind of load on a regular bases, I may need to give it another thought, probably by completely disabling this caching logic from the database abstraction layer, or at least, by allowing it to be disabled. It would need some testing though, to make sure it does not have a negative performance impact.

**Reply by rtrompier** [reply]
Since we have increase the RAM of our Redis instance to 4Gi we don't see anymore OOM.

Understood for the stress test. I just wait couple of hours to be sur the new version is stable before to run in production.

I work for the Geneva Hospitals, and we use Shlink to generate shorturl to send QR Code to our patients / visitor, so I can't send the new version without some tests ;) 

I come back to you in few hours with the result of my memory monitoring.

**Reply by acelaya** [reply]
It makes complete sense. Thanks for checking 🙂

**Comment by rtrompier** [comment]
Hi @acelaya,
Here is a little feedback about the memory usage of our 2 Shlink containers in our Staging env (light usage).

![image](https://user-images.githubusercontent.com/2504924/149086229-8b48d500-f2c3-422a-9259-3b51713f2cc9.png)

As you can see, the memory usage increase.
I'm gonna wait a few hours to see how the container is working when reach 100%.

**Reply by acelaya** [reply]
But that's under heavy load, right? Have you checked if it is reduced after 24h as expected?

**Reply by rtrompier** [reply]
I have stopped the stress test after the first hour.
So, now there is very low traffic on our staging env.

Sadly, after 24h, we didn't see the différence :/

**Reply by acelaya** [reply]
Can you check the TTL for some of the keys? Any key should be fine, as the vendor library is generating most of the stuff.

I just want to see if they expired and is just redis not doing a garbage collection for whatever reason, or they are not properly expiring.

In any case, I will go deeper into this. I don't get why is this library generating such massive amount of cache entries.

**Reply by rtrompier** [reply]
Just to be sure, I'm not talking anymore about the Redis container, but Shlink containers ;)

**Reply by rtrompier** [reply]
Little update from yesterday night :
![image](https://user-images.githubusercontent.com/2504924/149286893-ab8c0b87-36cd-4823-9707-a80306d48c99.png)

At 18:20 we have seen an OOM followed by a restart of the Shlink container due to Memory fully used

**Reply by acelaya** [reply]
Oh! I thought we were talking about redis memory consumption all the time.

Then a couple of questions pop-up:

* Is the issue with redis solved with v2.10.2?
* Did you ever experience this memory leak with previous Shlink versions, or did it start to happen with v2.10.2?

**Reply by rtrompier** [reply]
No problem, my bad.

The issue with Redis seem not be really solved. Until this morning I have no more OOM. but I have redeployed it this morning to add ports forwarding to check the datas present inside the container, and now the container is not starting (OOM due to lot of datas).

Concerning Shlink, i'm not sur, but I think its due to migration to cluster (2 instances + redis).
I'm gonna revert to only 1 instance and check the memory usage ;)

**Reply by acelaya** [reply]
Thanks, that's very helpful.

I'll create two separate tickets to investigate this a bit further.

**Comment by semangard** [comment]
Hello, my colleague @rtrompier still have the issue with only 1 instance ... 
@acelaya : could you please create tickets ? (do not hesitate to ask questions to @rtrompier if you need more details)

**Reply by acelaya** [reply]
Thanks for the clarification.

The issue will be investigated as part of this https://github.com/shlinkio/shlink/issues/1276

Depending on what I find out, I might back-port it to Shlink 2.10

**Reply by acelaya** [reply]
Could you, by any chance, share the env vars you are using (no need for the values)? Just to have an idea of what features are you using.

Also, when you say you experience this with only one instance, do you mean one Shlink instance using redis, or one Shlink instance without redis.

**Reply by rtrompier** [reply]
Hi @acelaya,
Here is a part of our docker-compose.
As you can see, we have only one instance of shlink server, without Redis (env var is commented).

```
shlink:
    image: shlinkio/shlink:2.10.2
    environment:
      DB_DRIVER: postgres
      DB_NAME: shlink
      DB_USER: shlink
      DB_PASSWORD: xxxxxxxx
      DB_HOST: shlink-postgres
      DB_PORT: 5432
      SHORT_DOMAIN_HOST: mydomain.ch
      SHORT_DOMAIN_SCHEMA: https
      DEFAULT_SHORT_CODES_LENGTH: 15
      GEOLITE_LICENSE_KEY: xxxxxxxxx
      # REDIS_SERVERS: tcp://shlink-redis:6379
    networks:
      - network
      - traefik_network
    depends_on: 
      - shlink-postgres
    healthcheck:
      test: ["CMD","curl","-s","--connect-timeout", "2","--max-time","5","--output","/dev/null","http://localhost:8080/rest/health"]
      interval: 10s
      timeout: 20s
      retries: 4
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.shlink-unsecure.rule=Host(`mydomain.ch`)"
        # - "traefik.http.routers.shlink-unsecure.middlewares=redirect@file"
        - "traefik.http.routers.shlink-unsecure.entrypoints=http"
        - "traefik.http.routers.shlink.rule=Host(`mydomain.ch`)"
        - "traefik.http.routers.shlink.tls=true"
        - "traefik.http.routers.shlink.entrypoints=https"
        - "traefik.http.services.shlink.loadbalancer.server.port=8080"
        # https://doc.traefik.io/traefik/routing/services/#health-check
        - "traefik.http.services.shlink.loadbalancer.healthCheck.path=/rest/health"
        - "traefik.http.services.shlink.loadbalancer.healthCheck.interval=30s"
        - "traefik.http.services.shlink.loadbalancer.healthCheck.timeout=20s"
        - "traefik.http.services.shlink.loadbalancer.healthCheck.scheme=http"
        - "traefik.http.services.shlink.loadbalancer.healthCheck.port=8080"
      replicas: 1
      placement:
        constraints:
          - node.role == worker
        preferences:
          - spread: node.labels.datacenter
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          cpus: "2"
          memory: 1G
```
