### DISCUSSION TITLE
Error when trying to edit settings (solution: incorrect database driver defined)

### DISCUSSION THREAD

**Discussion by eangulus** [shlinkio/discussions#6] [Help wanted] [answered]
### Shlink Dashboard version

latest

### Shlink version

latest

### How do you serve Shlink Dashboard

Docker image

### Database engine

MySQL

### Database version

10.11.11-MariaDB-0+deb12u1 - Debian 12

### Current behavior

When in the admin user and My Settings, non of the options are changable.

Like I cant turn on Dark theme, cant enable or disable any of the options.

In chrome Dev tools I get the following errors:

```
Uncaught RangeError: Too many properties to enumerate
    at j (index-BVtcHVV9.js:1:84)
    at index-D4H0zOig-BKKPqT6H.js:1:9986
    at index-D4H0zOig-BKKPqT6H.js:1:10139
    at onChange (index-D4H0zOig-BKKPqT6H.js:1:10763)
    at onChange (index-D4H0zOig-BKKPqT6H.js:1:5713)
    at index-WtS4KjPP.js:569:7182
    at yv (entry.client-Ca9ibxsd.js:24:116691)
    at entry.client-Ca9ibxsd.js:24:121689
    at Ti (entry.client-Ca9ibxsd.js:24:9041)
    at Nc (entry.client-Ca9ibxsd.js:24:117924)
```

### Expected behavior

I expect to be able to change the settings

### Minimum steps to reproduce

I simply created a stack in Portainer of both the API and the Dashboard using latest images.

after getting everything working, I logged into the dashboard using admin/admin created new password.

Then I went to admin at top right and selected my settings.

Then tried to change settings.

**Comment by acelaya** [comment]
I cannot reproduce it. Can you try to reproduce it in the simplest possible scenario? A docker compose config would be ideal.

**Comment by eangulus** [comment]
```yml
version: '3.8'
services:
  shlink-api:
    image: shlinkio/shlink:latest
    container_name: shlink-api
    restart: unless-stopped
    environment:
      - DEFAULT_DOMAIN=*****
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=mysql
      - DB_USER=*****
      - DB_PASSWORD=*****
      - DB_HOST=10.0.24.101
      - DB_NAME=shlink
      - SHELL_VERBOSITY=3
      - ENABLE_PERIODIC_VISIT_LOCATE=true
      - GEOLITE_LICENSE_KEY=*****
      - CORS_ALLOWED_ORIGINS=*
    ports:
      - "8080:8080"
    volumes:
      - /mnt/CONTAINER-DATA/SRV-DOCKER/shlink-api:/etc/shlink/data

  shlink-dashboard:
    image: shlinkio/shlink-dashboard:latest
    container_name: shlink-dashboard
    restart: unless-stopped
    depends_on:
      - shlink-api
    ports:
      - "8081:3005"
    environment:
      - SHLINK_DASHBOARD_DB_DRIVER=mysql
      - SHLINK_DASHBOARD_DB_HOST=10.0.24.101
      - SHLINK_DASHBOARD_DB_PORT=3306
      - SHLINK_DASHBOARD_DB_NAME=shlink_dashboard
      - SHLINK_DASHBOARD_DB_USER=*****
      - SHLINK_DASHBOARD_DB_PASSWORD=*****
      - NODE_ENV=production
    volumes:
      - /mnt/CONTAINER-DATA/SRV-DOCKER/shlink-dashboard:/app/data
```

Also, just want to note that in the main areas like adding links and such all the form controls seem fine. It is only under My Settings.

**Comment by eangulus** [comment]
And bear with me, please. I do work in IT, but I am very green with Docker.

I would not be surprised if the problem is my end.

**Comment by acelaya** [comment]
The first thing I see in that docker compose is that there's no database. Were you able to reproduce the issue consistently with that?

**Comment by eangulus** [comment]
No database? there is 2, shlink_dashboard and shlink both MySQL databases.

And yes, this is my compose and other than the issue described here, everything else works fine too.

**Comment by acelaya** [comment]
> No database? there is 2, shlink_dashboard and shlink both MySQL databases.

I mean there are no database containers defined in the docker compose you provided, so it's an incomplete reproduction. 

The reproduction needs to be a list of steps which ends up with a running environment where the issue can be consistently reproduced. 

I frequently suggest providing a docker compose because it forces issue reporters to replicate a simplified version of their environment, and in the process they usually find what they did wrong. 

And if you don't find anything wrong, at least you are providing me with a way to reproduce the issue with just `docker compose up`.

Skipping steps or making assumptions will end with me not being able to reproduce the issue, because I know how things work and therefore I'm biased. I need to see in detail what process you followed, to see what I could be missing. 

So long story short, your reproduction needs to include detailed information of how the database is set up, or in the case of docker compose, include database containers.

**Comment by eangulus** [comment]
So it's connected to a dedicated MySQL database (mariadb) with a user and pass that has full rights to it.

I simply created the databases and the containers made all the tables and data. I did go any further than create the 2 databases and the relevant user.

**Comment by acelaya** [comment]
I can't reproduce the issue using your docker compose with a MySQL database.

```yml
services:
  db_mysql:
    image: mysql:8.0.34
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shlink_dashboard
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  shlink-api:
    image: shlinkio/shlink:latest
    container_name: shlink-api
    restart: unless-stopped
    environment:
      - DEFAULT_DOMAIN=localhost:8080
      - IS_HTTPS_ENABLED=false
      - DB_DRIVER=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db_mysql
      - DB_NAME=shlink
      - SHELL_VERBOSITY=3
      - INITIAL_API_KEY=foobar
    ports:
      - "8080:8080"
    depends_on:
      db_mysql:
        condition: service_healthy

  shlink-dashboard:
    image: shlinkio/shlink-dashboard:latest
    container_name: shlink-dashboard
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SHLINK_DASHBOARD_DB_DRIVER=mysql
      - SHLINK_DASHBOARD_DB_HOST=db_mysql
      - SHLINK_DASHBOARD_DB_PORT=3306
      - SHLINK_DASHBOARD_DB_NAME=shlink_dashboard
      - SHLINK_DASHBOARD_DB_USER=root
      - SHLINK_DASHBOARD_DB_PASSWORD=root
      - NODE_ENV=production
      - SHLINK_DASHBOARD_PORT=8081
    depends_on:
      shlink-api:
        condition: service_started
      db_mysql:
        condition: service_healthy
```

I also removed the volumes, as you shouldn't need that, but I doubt that is the reason.

I'm going to need more precise information of your environment. What is the exact database version you are using (you mention MySQL, but then on the version it says MariaBD, so which one is it?)

I also need the exact sequence of steps you followed since the first log in with the initial admin user, until you experienced the issue for the first time.

Also, how did you notice the settings were not getting saved. Is it reflected in the UI clearly? Is there some error? Is it siply "unresponsive" and only the console error exists?

Regarding the `Uncaught RangeError: Too many properties to enumerate` console error, the trace references the minified production assets, so it's not easy to map that back to the actual source code. It would help if you could click in those files and screenshot what the browser shows. It's still going to be minified code, but it might be helpful nonetheless.
