### DISCUSSION TITLE
Issue with managed postgres database

### DISCUSSION THREAD

**Discussion by darkpixel** [shlinkio/discussions#72] [Help wanted] [answered]
I use a managed postgres database.

The 'shlink' database already exists.

When ```db:create``` is run, it attempts to connect to the postgres database even though it has no permission to connect to that database.  It fails:

```An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "--redacted-hostname--" (--redacted-ip--), port 25060 failed: FATAL:  database "postgres" does not exist ```

If I try to run ```db:migrate``` (skipping the creation of the database), I get:

```There is no table with name 'doadmin.short_urls' in the schema.```

In most apps that manage database schema (take Django migrations for example), they use different commands for creating the actual database verses populating the database with tables or schema changes instead of bundling them together into one action.

For a work-around, I'm going to spin up a local postgres instance in docker, run db:create and db:migrate, then export the database structure and import it into the managed database for my kubernetes cluster.

**Comment by acelaya** [comment]
I think there's a misconception here, as they are effectively two commands, `db:create` and `db:migrate`.

The first one creates the database schema, only if it does not exist, so usually just the first time. It is an idempotent command, and can be run as many times as you want with no errors.

The second one applies pending migrations, and requires the first one to have been successfully executed first, otherwise you might see the error above, related with missing tables. It is also idempotent, and the migrations do not include the initialization of the schema.

The problem here is that you seem to have provided the wrong database name to Shlink (it seems unlikely you want to use a database name "postgres"), or the user lacks sufficient permissions to initialize the database schema.

Also, these two commands are actually internal, and you shouldn't need to run them by yourself. The issue template requires you to provide some information about how you are running Shlink. Perhaps of you could provide that I would be able to guide you on next steps.

**Comment by darkpixel** [comment]
```db:create``` appears to create the database *AND* the schema.
In my case the managed database has already been created.

I double-checked, and the shlink container has an environment variable ```DB_NAME=shlink```.

In fact, if I create a database named ```postgres```, it completes the ```db:create``` command successfully and leaves a single table named ```migrations``` in the ```shlink``` database.  It has zero rows.

The startup still fails:
```
Creating fresh database if needed...
Updating database...

In Process.php line 267:
                                                                               
  The command "'/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-  
  migrations.php' 'migrations:migrate' '--no-interaction'" failed.             
                                                                               
  Exit Code: 10(Unknown error)                                                 
                                                                               
  Working directory: /etc/shlink                                               
                                                                               
  Output:                       

  Error Output:                                                                
  ================                                                             
                                                                               
  In SchemaException.php line 35:                                              
                                                                               
    There is no table with name 'doadmin.short_urls' in the schema.            
                                                                               
                                                                               
  migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--  
  allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CO  
  NFIGURATION] [--em EM] [--conn CONN] [--] [<version>]                        
                    
db:migrate
2022-03-01T03:23:44.921046388Z
```

I don't think the command is idemptent if it requires creating the database and the tables in one step, and if it fails to create the database because it already exists, it won't create the missing tables.

**Comment by acelaya** [comment]
Can you provide this information?

```
#### How Shlink is set-up

* Shlink Version: x.y.z
* PHP Version: x.y.z
* How do you serve Shlink: Self-hosted Apache|Self-hosted nginx|Self-hosted openswoole|Docker image
* Database engine used: MySQL|MariaDB|PostgreSQL|MicrosoftSQL|SQLite (x.y.z)
```

Some reproducible steps would be nice as well, via a docker-compose file or similar.

**Comment by darkpixel** [comment]
I'm using a Digital Ocean managed Postgres 14 database.
I pulled the ```shlink:stable``` container into my Kubernetes cluster a few hours ago.  The container has PHP 8.1.3 installed.
I'm not sure where to find the version number of shlink inside the container.  It doesn't look like /etc/shlink is a git repo.
I'm using ingress-nginx to serve shlink

**Comment by darkpixel** [comment]
To reproduce:
Great an account with Digital Ocean.
Create a managed database cluster.
Create a 'shlink' database.
Create a 'shlink' user.
Create a kubernetes cluster.

Here's the kubernetes config:
```
apiVersion: v1
kind: Namespace
metadata:
  name: shlink

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shlink-config
  namespace: shlink
data:
  DEFAULT_DOMAIN: "mydomain.com"
  IS_HTTPS_ENABLED: "true"
  DB_DRIVER: "postgres"
  DB_NAME: "shlink"
  DB_USER: "doadmin"
  DB_PASSWORD: "mypassword"
  DB_HOST: "mydbhost"
  DB_PORT: "25060"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mydomain-com
  namespace: shlink
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/load-balance: "ewma"
spec:
  tls:
  - hosts:
      - mydomain.com
    secretName: mydomain.com-tls
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shlink
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: shlink
  namespace: shlink
  labels:
    app: shlink
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mydomain.com
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8080
  selector:
    app: shlink

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink
  namespace: shlink
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "5%"
      maxSurge: "90%"
  selector:
    matchLabels:
      app: shlink
  template:
    metadata:
      labels:
        app: shlink
    spec:
      #      securityContext:
      #        runAsNonRoot: true
      #        runAsUser: 1000
      containers:
      - name: shlink
        image: shlinkio/shlink:stable
        ports:
        - containerPort: 8080
          #        resources:
          #          requests:
          #            memory: "128Mi"
          #            cpu: ".1"
          #          limits:
          #            memory: "128Mi"
          #            cpu: ".1"
        envFrom:
          - configMapRef:
              name: shlink-config
        imagePullPolicy: Always
```
