### DISCUSSION TITLE
Docker cant resolve to DB

### DISCUSSION THREAD

**Discussion by the-hotmann** [shlinkio/discussions#79] [Help wanted]
#### How Shlink is set-up

* Shlink Version: 3.0.3
* PHP Version: 8.1.3
* How do you serve Shlink: Docker image (want to switcvh from selfhosted)
* Database engine used: MariaDB

#### Summary
```
db:create


In ExceptionConverter.php line 103:
                                                                               
  An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_get  
  addresses: getaddrinfo for "sub.domain.tld" failed: Name does not   
  resolve                                                                      
                                                                               

In Exception.php line 30:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for "sub.domain.tld" failed: Name does not resolve
```
domain was censored to "`sub.domain.tld`"

Additional docker log:

```
./updateShlink.sh
WARNING: The LHDaa variable is not set. Defaulting to a blank string.
Pulling shlink ... done
```

Maybe related to https://github.com/docker/compose/issues/4189?

BTW, my docker-compose:

```
version: "3.8"
services:
  shlink:
    image: shlinkio/shlink:stable
    restart: unless-stopped
    container_name: shlink
    environment:
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY="GeoLITELicense"
      - DEFAULT_DOMAIN="serve.domain.tld"
      - WEB_WORKER_NUM="50"
      - TASK_WORKER_NUM="50"
      - DB_DRIVER="maria"
      - DB_NAME="NAME"
      - DB_USER="USER"
      - DB_PASSWORD="PASSWORD"
      - DB_HOST="sub.domain.tld"
      - DB_PORT="3306"
      - REDIRECT_STATUS_CODE="302"
      - DEFAULT_INVALID_SHORT_URL_REDIRECT="https://sub.domain.tld/404"
      - DEFAULT_REGULAR_404_REDIRECT="https://sub.domain.tld/404"
      - DEFAULT_BASE_URL_REDIRECT="https://sub.domain.tld"
      - REDIRECT_APPEND_EXTRA_PATH=false
      - DISABLE_TRACKING=false
      - TRACK_ORPHAN_VISITS=true
      - ANONYMIZE_REMOTE_ADDR=false
      - DISABLE_UA_TRACKING=false
      - DISABLE_REFERRER_TRACKING=false
      - ENABLE_PERIODIC_VISIT_LOCATE=true
    ports:
      - 8080:8080
```

(again censored some info for privacy reasons)
